apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    vault:
      server: {{ .Values.vault.serverURL | quote }}
      path: {{ .Values.vault.kvMountPath | quote }}
      version: v2
      auth:
        tokenSecretRef:
          name: vault-root-token
          namespace: {{ .Values.esoNamespace }}
          key: token
