{{- if .Values.demoExternalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.demoExternalSecret.name }}
  namespace: {{ .Values.esoNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: {{ .Values.demoExternalSecret.refreshInterval }}
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.demoExternalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.demoExternalSecret.targetSecretKey }}
      remoteRef:
        key: {{ .Values.demoExternalSecret.remote.path }}
        property: {{ .Values.demoExternalSecret.remote.property }}
{{- end }}
