{{- $ns := .Values.esoNamespace }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
type: Opaque
stringData:
  token: {{ .Values.vault.rootToken | quote }}
