apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-directory-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        # Poll Git for directory changes (default 180s). Ref:
        # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#git-polling-interval
        requeueAfterSeconds: 60
        repoURL: https://github.com/gac3k/k8s-sample-app-of-apps.git
        revision: HEAD
        directories:
          - path: helm/*/*/*
  template:
    metadata:
      name: '{{index .path.segments 3}}-{{index .path.segments 2}}-{{index .path.segments 1}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/gac3k/k8s-sample-app-of-apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          releaseName: '{{index .path.segments 3}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
