apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform applications managed by Argo CD
  sourceRepos:
    - git@github.com:Mindsec-io/*
    - https://github.com/Mindsec-io/*
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

