{{- if .Values.gitWriteBackExternalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.gitWriteBackExternalSecret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.gitWriteBackExternalSecret.syncWave | quote }}
spec:
  refreshInterval: {{ .Values.gitWriteBackExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.gitWriteBackExternalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.gitWriteBackExternalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: {{ .Values.gitWriteBackExternalSecret.vault.path }}
        property: {{ .Values.gitWriteBackExternalSecret.vault.property }}
{{- end }}
